import Phaser from 'phaser';import { EMPTY,GREY,ORANGE,cloneGrid,type CellValue,type Grid,type Level,type Position } from '../core/model';import { includesPosition,validateGrid } from '../core/validator';import { AudioService } from '../services/AudioService';import { HapticsService } from '../services/HapticsService';

interface CellView {container:Phaser.GameObjects.Container;bg:Phaser.GameObjects.Graphics;cat:Phaser.GameObjects.Image|undefined;preset:boolean;r:number;c:number}
export class BoardView extends Phaser.GameObjects.Container {
  readonly grid:Grid;private cells:CellView[]=[];private readonly boardSize:number;private readonly inset:number;private readonly tile:number;errors=0;onChanged?:()=>void;
  constructor(scene:Phaser.Scene,x:number,y:number,readonly level:Level,boardSize:number){super(scene,x,y);scene.add.existing(this);this.grid=cloneGrid(level.initial);this.boardSize=boardSize;this.inset=boardSize*.115;this.tile=(boardSize-this.inset*2)/level.size;const frame=scene.add.image(0,0,'board-frame').setDisplaySize(boardSize,boardSize);this.add(frame);this.buildCells();this.buildConstraints();}
  private buildCells(){const start=-this.boardSize/2+this.inset;for(let r=0;r<this.level.size;r++)for(let c=0;c<this.level.size;c++){const x=start+c*this.tile+this.tile/2,y=start+r*this.tile+this.tile/2;const holder=this.scene.add.container(x,y);const bg=this.scene.add.graphics();this.drawCell(bg,0xfff4e7,0xdba77b);holder.add(bg);const preset=this.level.initial[r]![c]!==EMPTY;const cell:CellView={container:holder,bg,cat:undefined,preset,r,c};this.cells.push(cell);this.add(holder);if(this.grid[r]![c]!==EMPTY)this.setCat(cell,this.grid[r]![c]!,false);if(!preset)holder.setSize(this.tile*.88,this.tile*.88).setInteractive({useHandCursor:true}).on('pointerdown',()=>this.cycle(cell));}}
  private drawCell(g:Phaser.GameObjects.Graphics,fill:number,stroke:number){const s=this.tile*.84;g.clear().fillStyle(fill,1).lineStyle(Math.max(2,this.tile*.025),stroke,.65).fillRoundedRect(-s/2,-s/2,s,s,this.tile*.14).strokeRoundedRect(-s/2,-s/2,s,s,this.tile*.14);}
  private setCat(cell:CellView,value:CellValue,animate=true){cell.cat?.destroy();cell.cat=undefined;if(value===EMPTY)return;const small=this.level.size===8;const texture=value===GREY?(small?'grey-small':'grey-cat'):(small?'orange-small':'orange-cat');const image=this.scene.add.image(0,0,texture);const max=this.tile*(this.level.size===4?.76:.70);image.setScale(Math.min(max/image.width,max/image.height));if(cell.preset)image.setAlpha(.88);cell.container.add(image);cell.cat=image;if(animate&&!matchMedia('(prefers-reduced-motion: reduce)').matches){image.setScale(image.scaleX*.65,image.scaleY*.65).setAlpha(.3);this.scene.tweens.add({targets:image,scaleX:image.scaleX/0.65,scaleY:image.scaleY/0.65,alpha:1,duration:190,ease:'Back.Out'});}}
  private cycle(cell:CellView){const current=this.grid[cell.r]![cell.c]!;const next:CellValue=current===EMPTY?GREY:current===GREY?ORANGE:EMPTY;this.grid[cell.r]![cell.c]=next;this.setCat(cell,next);AudioService.play('place');void HapticsService.light();const result=validateGrid(this.grid,this.level.constraints);if(result.errors.length){this.errors++;AudioService.play('invalid');void HapticsService.error();this.scene.tweens.add({targets:cell.container,x:`+=${this.tile*.05}`,duration:45,yoyo:true,repeat:3});}this.paintErrors(result.errors);this.onChanged?.();}
  private paintErrors(errors:Position[]){for(const cell of this.cells)this.drawCell(cell.bg,includesPosition(errors,cell.r,cell.c)?0xffd3d2:0xfff4e7,includesPosition(errors,cell.r,cell.c)?0xef5a62:0xdba77b);}
  private buildConstraints(){const start=-this.boardSize/2+this.inset;for(const constraint of this.level.constraints){const [ar,ac]=constraint.a,[br,bc]=constraint.b;const x=start+((ac+bc)/2+.5)*this.tile,y=start+((ar+br)/2+.5)*this.tile;const image=this.scene.add.image(x,y,constraint.type==='same'?'same':'different');const scale=Math.min(this.tile*.29/image.width,this.tile*.29/image.height);image.setScale(scale).setDepth(20);this.add(image);}}
  reset(){for(const cell of this.cells){this.grid[cell.r]![cell.c]=this.level.initial[cell.r]![cell.c]!;this.setCat(cell,this.grid[cell.r]![cell.c]!,false);}this.paintErrors([]);this.errors=0;this.onChanged?.();}
  reveal(position:Position,value:CellValue){const cell=this.cells.find(x=>x.r===position[0]&&x.c===position[1]);if(!cell||cell.preset)return;this.grid[cell.r]![cell.c]=value;this.setCat(cell,value);this.drawCell(cell.bg,0xfff2bb,0xffbd35);this.scene.tweens.add({targets:cell.container,scale:1.14,duration:160,yoyo:true});this.onChanged?.();}
}
