import Phaser from 'phaser';
import { EMPTY,GREY,ORANGE,cloneGrid,type CellValue,type Grid,type Level,type Position } from '../core/model';
import { includesPosition,validateGrid } from '../core/validator';
import { AudioService } from '../services/AudioService';
import { HapticsService } from '../services/HapticsService';
import { SaveService } from '../services/SaveService';
import { relationIcon,sparkles } from './ui';
interface CellView {container:Phaser.GameObjects.Container;bg:Phaser.GameObjects.Graphics;cat:Phaser.GameObjects.Image|undefined;preset:boolean;r:number;c:number}
export class BoardView extends Phaser.GameObjects.Container {
 readonly grid:Grid;private cells:CellView[]=[];private readonly tile:number;private history:Grid[]=[];private links:{icon:Phaser.GameObjects.Container;index:number;satisfied:boolean}[]=[];private completeLines=new Set<string>();errors=0;locked=false;brush:CellValue=GREY;onChanged?:()=>void;onAttempt?:()=>void;
 constructor(scene:Phaser.Scene,x:number,y:number,readonly level:Level,private readonly boardSize:number){super(scene,x,y);scene.add.existing(this);this.grid=cloneGrid(level.initial);this.tile=(boardSize-44)/level.size;const frame=scene.add.graphics();frame.fillStyle(0x776484,.18).fillRoundedRect(-boardSize/2,-boardSize/2+18,boardSize,boardSize,44).fillStyle(0xd4a16b).fillRoundedRect(-boardSize/2,-boardSize/2,boardSize,boardSize,44).lineStyle(5,0xffffff).strokeRoundedRect(-boardSize/2,-boardSize/2,boardSize,boardSize,44);this.add(frame);this.buildCells();this.buildConstraints();}
 private buildCells(){const start=-this.boardSize/2+22;for(let r=0;r<this.level.size;r++)for(let c=0;c<this.level.size;c++){const holder=this.scene.add.container(start+c*this.tile+this.tile/2,start+r*this.tile+this.tile/2),bg=this.scene.add.graphics();holder.add(bg);const preset=this.level.initial[r]![c]!==EMPTY,cell:CellView={container:holder,bg,cat:undefined,preset,r,c};this.cells.push(cell);this.add(holder);this.paintCell(cell,false);this.setCat(cell,this.grid[r]![c]!,false);if(!preset)holder.setSize(this.tile*.94,this.tile*.94).setInteractive({useHandCursor:true}).on('pointerup',(p:Phaser.Input.Pointer)=>{if(p.getDistance()<20)this.cycle(cell);});}}
 private paintCell(cell:CellView,error:boolean,hint=false){const value=this.grid[cell.r]![cell.c]!,s=this.tile*.92;const fill=error?0xffe2e5:hint?0xffedb4:value===GREY?0xeee8f7:value===ORANGE?0xffe9d4:0xfffbf7;cell.bg.clear().fillStyle(0x9580a1,.2).fillRoundedRect(-s/2,-s/2+4,s,s,18).fillStyle(fill).lineStyle(error?4:2,error?0xd96e8c:0xffffff).fillRoundedRect(-s/2,-s/2,s,s,18).strokeRoundedRect(-s/2,-s/2,s,s,18);if(cell.preset){cell.bg.lineStyle(3,0x82708d).strokeRoundedRect(s*.3-5,-s*.39,10,9,3);cell.bg.fillStyle(0x82708d).fillRoundedRect(s*.3-8,-s*.34,16,12,3);}}
 private setCat(cell:CellView,value:CellValue,animate=true){cell.cat?.destroy();cell.cat=undefined;if(value===EMPTY)return;const image=this.scene.add.image(0,2,value===GREY?'grey-cat':'orange-cat');const scale=this.tile*.76/Math.max(image.width,image.height);image.setScale(scale);cell.container.add(image);cell.cat=image;if(animate&&!SaveService.data.settings.reducedMotion){image.setScale(scale*.65);this.scene.tweens.add({targets:image,scaleX:scale,scaleY:scale,duration:230,ease:'Back.Out'});}}
 private cycle(cell:CellView){if(this.locked)return;this.onAttempt?.();const current=this.grid[cell.r]![cell.c]!,next:CellValue=current===this.brush?EMPTY:this.brush;
 if(next!==EMPTY&&next!==this.level.solution[cell.r]![cell.c]){this.errors++;AudioService.play('invalid');void HapticsService.error();this.paintCell(cell,true);this.scene.time.delayedCall(220,()=>{if(this.scene.sys.isActive())this.paintCell(cell,false);});if(this.errors>=3)this.locked=true;this.onChanged?.();return;}
 this.history.push(cloneGrid(this.grid));this.grid[cell.r]![cell.c]=next;this.setCat(cell,next);AudioService.play('place');void HapticsService.light();this.paintErrors([]);this.onChanged?.();}
 private paintErrors(errors:Position[]){for(const cell of this.cells)this.paintCell(cell,includesPosition(errors,cell.r,cell.c));
 for(const link of this.links){const con=this.level.constraints[link.index]!,a=this.grid[con.a[0]]![con.a[1]],b=this.grid[con.b[0]]![con.b[1]],ok=!!a&&!!b&&(con.type==='same'?a===b:a!==b);if(ok&&!link.satisfied&&!SaveService.data.settings.reducedMotion)this.scene.tweens.add({targets:link.icon,scaleX:1.25,scaleY:1.25,duration:150,yoyo:true});link.satisfied=ok;}
 for(const vertical of [false,true])for(let i=0;i<this.level.size;i++){const positions=this.cells.filter(c=>vertical?c.c===i:c.r===i),key=`${vertical}:${i}`,complete=positions.every(c=>this.grid[c.r]![c.c]!==EMPTY&&!includesPosition(errors,c.r,c.c));if(complete&&!this.completeLines.has(key)){this.completeLines.add(key);if(!SaveService.data.settings.reducedMotion)positions.forEach((cell,j)=>this.scene.tweens.add({targets:cell.bg,alpha:.55,duration:160,delay:j*55,yoyo:true}));}else if(!complete)this.completeLines.delete(key);}
 }
 highlight(positions:readonly Position[]){for(const cell of this.cells)if(includesPosition(positions,cell.r,cell.c))this.paintCell(cell,false,true);}
 private buildConstraints(){const start=-this.boardSize/2+22;for(const constraint of this.level.constraints){const [ar,ac]=constraint.a,[br,bc]=constraint.b,x=start+((ac+bc)/2+.5)*this.tile,y=start+((ar+br)/2+.5)*this.tile;const icon=relationIcon(this.scene,x,y,this.tile*.32,constraint.type==='same');this.add(icon);this.links.push({icon,index:this.links.length,satisfied:false});}}
 restore(grid:Grid,errors:number){if(grid.length!==this.level.size||grid.some((row,r)=>row.length!==this.level.size||row.some((v,c)=>![0,1,2].includes(v)||(this.level.initial[r]![c]!==EMPTY&&v!==this.level.initial[r]![c]))))return;for(const cell of this.cells){this.grid[cell.r]![cell.c]=grid[cell.r]![cell.c]===this.level.solution[cell.r]![cell.c]?grid[cell.r]![cell.c]!:this.level.initial[cell.r]![cell.c]!;this.setCat(cell,this.grid[cell.r]![cell.c]!,false);}this.errors=Math.max(0,errors);this.paintErrors(validateGrid(this.grid,this.level.constraints).errors);}
 reset(){this.history.push(cloneGrid(this.grid));this.restore(this.level.initial,this.errors);this.onChanged?.();}
 undo(){if(this.locked)return;const last=this.history.pop();if(last){this.restore(last,this.errors);this.onChanged?.();}}
 reveal(position:Position,value:CellValue){const cell=this.cells.find(x=>x.r===position[0]&&x.c===position[1]);if(!cell||cell.preset||this.locked)return;this.history.push(cloneGrid(this.grid));this.grid[cell.r]![cell.c]=value;this.paintErrors(validateGrid(this.grid,this.level.constraints).errors);this.paintCell(cell,false,true);this.setCat(cell,value);sparkles(this.scene,this.x+cell.container.x,this.y+cell.container.y,6);this.onChanged?.();}
}
