import Phaser from 'phaser';
import { EMPTY,GREY,cloneGrid,type CellValue,type Grid,type Level,type Position } from '../core/model';
import { includesPosition,validateGrid } from '../core/validator';
import { AudioService } from '../services/AudioService';
import { HapticsService } from '../services/HapticsService';
import { SaveService } from '../services/SaveService';
import { relationIcon,sparkles } from './ui';
interface CellView {container:Phaser.GameObjects.Container;bg:Phaser.GameObjects.Image;cat:Phaser.GameObjects.Image|undefined;preset:boolean;r:number;c:number}
export class BoardView extends Phaser.GameObjects.Container {
 readonly grid:Grid;private cells:CellView[]=[];private readonly tile:number;private readonly inset:number;private readonly cellScale:number;private links:{icon:Phaser.GameObjects.Container;index:number;satisfied:boolean}[]=[];private completeLines=new Set<string>();errors=0;locked=false;brush:CellValue=GREY;onChanged?:()=>void;onAttempt?:()=>void;onPlacement?:(correct:boolean)=>void;
 constructor(scene:Phaser.Scene,x:number,y:number,readonly level:Level,private readonly boardSize:number){
  super(scene,x,y);scene.add.existing(this);this.grid=cloneGrid(level.initial);this.inset=level.size===8?0:36;this.cellScale=level.size===8?.99:.9;this.tile=(boardSize-this.inset*2)/level.size;
  const frameSize=level.size===8?1080:boardSize+30;const frame=scene.add.image(0,0,'puzzle-board-frame').setDisplaySize(frameSize,frameSize);
  this.add(frame);this.buildCells();this.buildConstraints();
 }
 private buildCells(){const start=-this.boardSize/2+this.inset;for(let r=0;r<this.level.size;r++)for(let c=0;c<this.level.size;c++){const holder=this.scene.add.container(start+c*this.tile+this.tile/2,start+r*this.tile+this.tile/2),bg=this.scene.add.image(0,0,'cell-empty').setDisplaySize(this.tile*this.cellScale,this.tile*this.cellScale);holder.add(bg);const preset=this.level.initial[r]![c]!==EMPTY,cell:CellView={container:holder,bg,cat:undefined,preset,r,c};this.cells.push(cell);this.add(holder);this.paintCell(cell,false);this.setCat(cell,this.grid[r]![c]!,false);if(!preset){let downX=0,downY=0,pointerId=-1;holder.setSize(this.tile*.98,this.tile*.98).setInteractive({useHandCursor:true}).on('pointerdown',(p:Phaser.Input.Pointer)=>{downX=p.x;downY=p.y;pointerId=p.id;if(!SaveService.data.settings.reducedMotion)this.scene.tweens.add({targets:holder,scaleX:.97,scaleY:.97,duration:70});}).on('pointerup',(p:Phaser.Input.Pointer)=>{holder.setScale(1);if(p.id!==pointerId)return;pointerId=-1;const dx=p.x-downX,dy=p.y-downY;const dragTolerance=Math.max(24,this.tile*.28);if(dx*dx+dy*dy<=dragTolerance*dragTolerance)this.place(cell);}).on('pointerout',(p:Phaser.Input.Pointer)=>{holder.setScale(1);if(p.id===pointerId&&p.isDown){const dx=p.x-downX,dy=p.y-downY;if(dx*dx+dy*dy>this.tile*this.tile*.16)pointerId=-1;}});}}}
 private paintCell(cell:CellView,error:boolean,hint=false){cell.bg.setTexture(error?'cell-error':hint?'cell-hint':'cell-empty').setDisplaySize(this.tile*this.cellScale,this.tile*this.cellScale);if(cell.preset)cell.bg.setTint(0xf2e7df);else cell.bg.clearTint();}
 private setCat(cell:CellView,value:CellValue,animate=true){cell.cat?.destroy();cell.cat=undefined;if(value===EMPTY)return;const image=this.scene.add.image(0,2,value===GREY?'grey-cat':'orange-cat');const scale=this.tile*.84/Math.max(image.width,image.height);image.setScale(scale);cell.container.add(image);cell.cat=image;if(animate&&!SaveService.data.settings.reducedMotion){image.setScale(scale*.72,scale*.55).setY(10);this.scene.tweens.add({targets:image,scaleX:scale*1.05,scaleY:scale*1.05,y:0,duration:190,ease:'Back.Out',onComplete:()=>this.scene.tweens.add({targets:image,scaleX:scale,scaleY:scale,duration:90,ease:'Sine.Out'})});}}
 private place(cell:CellView){if(this.locked||cell.preset||this.grid[cell.r]![cell.c]!==EMPTY)return;this.onAttempt?.();const next=this.brush,correct=next===this.level.solution[cell.r]![cell.c];this.onPlacement?.(correct);
  if(!correct){this.errors++;AudioService.play('invalid');void HapticsService.error();this.paintCell(cell,true);if(!SaveService.data.settings.reducedMotion)this.scene.tweens.add({targets:cell.container,x:cell.container.x+8,duration:55,yoyo:true,repeat:3,ease:'Sine.InOut'});this.scene.time.delayedCall(240,()=>{if(this.scene.sys.isActive())this.paintCell(cell,false);});if(this.errors>=3)this.locked=true;this.onChanged?.();return;}
  this.grid[cell.r]![cell.c]=next;this.paintCell(cell,false);this.setCat(cell,next);AudioService.play('place');void HapticsService.light();this.updateFeedback(cell);this.onChanged?.();}
 private updateFeedback(changed?:CellView,errors:Position[]=[]){
  for(const link of this.links){const con=this.level.constraints[link.index]!,a=this.grid[con.a[0]]![con.a[1]],b=this.grid[con.b[0]]![con.b[1]],ok=!!a&&!!b&&(con.type==='same'?a===b:a!==b);if(ok&&!link.satisfied&&!SaveService.data.settings.reducedMotion)this.scene.tweens.add({targets:link.icon,scaleX:1.25,scaleY:1.25,duration:150,yoyo:true});link.satisfied=ok;}
  const lines=changed?[{vertical:false,index:changed.r},{vertical:true,index:changed.c}]:Array.from({length:this.level.size*2},(_,i)=>({vertical:i>=this.level.size,index:i%this.level.size}));
  for(const {vertical,index:i} of lines){const positions=this.cells.filter(c=>vertical?c.c===i:c.r===i),key=`${vertical}:${i}`,complete=positions.every(c=>this.grid[c.r]![c.c]!==EMPTY&&!includesPosition(errors,c.r,c.c));if(complete&&!this.completeLines.has(key)){this.completeLines.add(key);if(!SaveService.data.settings.reducedMotion)positions.forEach((cell,j)=>this.scene.tweens.add({targets:cell.bg,alpha:.48,duration:140,delay:j*42,yoyo:true}));}else if(!complete)this.completeLines.delete(key);}
 }
 private paintErrors(errors:Position[],repaint=true){if(repaint)for(const cell of this.cells)this.paintCell(cell,includesPosition(errors,cell.r,cell.c));this.updateFeedback(undefined,errors);}
 highlight(positions:readonly Position[]){for(const cell of this.cells)if(includesPosition(positions,cell.r,cell.c))this.paintCell(cell,false,true);}
 private buildConstraints(){const start=-this.boardSize/2+this.inset;for(const constraint of this.level.constraints){const [ar,ac]=constraint.a,[br,bc]=constraint.b,x=start+((ac+bc)/2+.5)*this.tile,y=start+((ar+br)/2+.5)*this.tile;const icon=relationIcon(this.scene,x,y,this.tile*.32,constraint.type==='same');this.add(icon);this.links.push({icon,index:this.links.length,satisfied:false});}}
 restore(grid:Grid,errors:number){if(grid.length!==this.level.size||grid.some((row,r)=>row.length!==this.level.size||row.some((v,c)=>![0,1,2].includes(v)||(this.level.initial[r]![c]!==EMPTY&&v!==this.level.initial[r]![c]))))return;for(const cell of this.cells){this.grid[cell.r]![cell.c]=grid[cell.r]![cell.c]===this.level.solution[cell.r]![cell.c]?grid[cell.r]![cell.c]!:this.level.initial[cell.r]![cell.c]!;this.setCat(cell,this.grid[cell.r]![cell.c]!,false);}this.errors=Math.max(0,errors);this.paintErrors(validateGrid(this.grid,this.level.constraints).errors);}
 reveal(position:Position,value:CellValue){const cell=this.cells.find(x=>x.r===position[0]&&x.c===position[1]);if(!cell||cell.preset||this.locked||this.grid[cell.r]![cell.c]!==EMPTY)return;this.grid[cell.r]![cell.c]=value;this.paintCell(cell,false,true);this.setCat(cell,value);this.updateFeedback(cell);sparkles(this.scene,this.x+cell.container.x,this.y+cell.container.y,6);this.onChanged?.();}
}
