import Phaser from 'phaser';
import { cosmetics,starterCosmetics } from '../../core/cosmetics';
import { SaveService } from '../../services/SaveService';
import { backgroundTextureForId,backButton,button,cozyBackground,imageContain,label,panel,press,title } from '../ui';
import { C } from '../theme';

export class LostScene extends Phaser.Scene {
 constructor(){super('Lost');}
 create({reason='errors'}:{reason?:string}={}){cozyBackground(this);panel(this,540,1000,900,1180);title(this,'Chat alors…',410,72);imageContain(this.add.image(540,850,'duo-retry'),650,430).setDepth(30);label(this,540,1060,reason==='time'?'Le temps est écoulé.':'Trois erreurs mettent fin à cette tentative.',35);label(this,540,1160,'Tu peux recommencer gratuitement.\nLa grille, le cœur, le chrono et les indices repartent de zéro.',27);button(this,540,1390,690,'Recommencer',()=>{SaveService.restartAttempt();this.scene.start('Game');},C.teal);button(this,540,1550,690,'Retour à l’arbre',()=>this.scene.start('LevelSelect'),C.orange);}
}

type ShopTab='standard'|'rare';
export class ShopScene extends Phaser.Scene {
 private tab:ShopTab='standard';private selectedOffer=0;
 constructor(){super('Shop');}
 init(data:{tab?:ShopTab;selected?:number}={}){this.tab=data.tab??'standard';this.selectedOffer=Math.max(0,data.selected??0);}
 create(){
  this.cameras.main.setBackgroundColor(0xfff7ef);backButton(this,()=>this.scene.start('LevelSelect'));title(this,'Boutique',90,58);label(this,540,150,'Des trouvailles pour personnaliser ton arbre',26,'#78647d',18);
  const wallet=this.add.container(540,250),walletSkin=this.add.image(0,0,'button-secondary').setDisplaySize(620,108),kibble=imageContain(this.add.image(-190,0,'hub-kibble'),66,66),amount=label(this,-85,0,String(SaveService.data.kibble),34,C.ink,20);wallet.add([walletSkin,kibble,amount]);label(this,675,250,'Croquettes',25,'#78647d',18);
  const tabY=370,tabW=500,gap=22,start=29;([{key:'standard' as const,name:'Standards'},{key:'rare' as const,name:'Rares'}]).forEach((t,i)=>{const active=this.tab===t.key,c=this.add.container(start+tabW/2+i*(tabW+gap),tabY),skin=this.add.image(0,0,active?'button-primary':'button-secondary').setDisplaySize(tabW,108),txt=label(this,0,0,t.name,30,active?'#ffffff':C.ink,20);c.add([skin,txt]);if(!active)c.setAlpha(.9);press(this,c,tabW,108,()=>this.scene.restart({tab:t.key,selected:0}));});
  if(this.tab==='rare'){imageContain(this.add.image(540,720,'diamond-chest'),250,250);label(this,540,930,'Les objets rares arriveront avec les diamants.',30,C.ink,20);label(this,540,990,'Ils resteront secrets avant leur découverte.',22,'#78647d',18);return;}
  const all=cosmetics.filter(c=>!starterCosmetics.includes(c.id)),unowned=all.filter(c=>!SaveService.data.ownedCosmetics.includes(c.id)),owned=all.filter(c=>SaveService.data.ownedCosmetics.includes(c.id)),offers=[...unowned,...owned].slice(0,6),prices=[80,100,120,140,160,180];this.selectedOffer=Math.min(this.selectedOffer,Math.max(0,offers.length-1));
  offers.forEach((item,i)=>{const col=i%3,row=Math.floor(i/3),x=190+col*350,y=620+row*390,selected=i===this.selectedOffer;const card=panel(this,x,y,310,350);if(selected)card.setTint(0xfff3d7);if(item.slot==='background')imageContain(this.add.image(x,y-70,backgroundTextureForId(item.id)),205,138);else if(item.slot==='cushion')imageContain(this.add.image(x,y-68,'tree-flower-cushion'),178,138).setTint(item.color);else{const texture=item.id==='birch'?'tree-cubby-cream':item.id==='walnut'?'tree-cubby':'tree-cubby-wood';imageContain(this.add.image(x,y-68,texture),162,152);}label(this,x,y+28,item.name,23,C.ink,18).setWordWrapWidth(260);const isOwned=SaveService.data.ownedCosmetics.includes(item.id),equipped=SaveService.data.equipped[item.slot]===item.id,price=prices[i]!,action=this.add.container(x,y+108),skin=this.add.image(0,0,isOwned?'button-disabled':'button-primary').setDisplaySize(250,78),icon=isOwned?null:imageContain(this.add.image(-68,0,'hub-kibble'),36,36),txt=label(this,isOwned?0:22,0,equipped?'Équipé':isOwned?'Possédé':String(price),22,isOwned?C.ink:'#ffffff',18);action.add(skin);if(icon)action.add(icon);action.add(txt);if(!isOwned)press(this,action,250,78,()=>{if(SaveService.data.kibble<price)return;SaveService.data.kibble-=price;SaveService.data.ownedCosmetics.push(item.id);void SaveService.persist();this.scene.restart({tab:this.tab,selected:i});});const pick=this.add.container(x,y-42);press(this,pick,300,220,()=>this.scene.restart({tab:this.tab,selected:i}));});
  const selected=offers[this.selectedOffer];if(selected){const isOwned=SaveService.data.ownedCosmetics.includes(selected.id),equipped=SaveService.data.equipped[selected.slot]===selected.id;panel(this,540,1585,1000,230);label(this,330,1518,'Aperçu sur ton arbre',23,'#78647d',18);if(selected.slot==='background')imageContain(this.add.image(175,1585,backgroundTextureForId(selected.id)),205,145);else{imageContain(this.add.image(170,1605,'tree-post-short'),66,160);imageContain(this.add.image(170,1538,'tree-support-cream'),180,84);if(selected.slot==='cushion')imageContain(this.add.image(170,1525,'tree-flower-cushion'),112,88).setTint(selected.color);else imageContain(this.add.image(170,1534,selected.id==='birch'?'tree-cubby-cream':selected.id==='walnut'?'tree-cubby':'tree-cubby-wood'),116,116);}label(this,320,1566,selected.name,28,C.ink,18).setOrigin(0,.5);label(this,320,1608,equipped?'Actuellement équipé':isOwned?'Possédé · prêt à équiper':'Disponible dans la boutique',19,'#78647d',16).setOrigin(0,.5);if(isOwned&&!equipped){const equip=this.add.container(850,1585),skin=this.add.image(0,0,'button-primary').setDisplaySize(250,82),txt=label(this,0,0,'Équiper',23,'#ffffff',18);equip.add([skin,txt]);press(this,equip,250,82,()=>{SaveService.data.equipped[selected.slot]=selected.id;void SaveService.persist().then(()=>this.scene.restart({tab:this.tab,selected:this.selectedOffer}));});}else if(equipped){const state=this.add.container(850,1585),skin=this.add.image(0,0,'button-disabled').setDisplaySize(250,82),check=imageContain(this.add.image(-62,0,'ui-check'),34,34),txt=label(this,20,0,'Équipé',22,C.ink,18);state.add([skin,check,txt]);}}
 }
}

type MissionTab='daily'|'global';
type GlobalDef={id:string;title:string;icon:string;value:()=>number;thresholds:number[];collection?:boolean};
type MissionReward={icon:string;amount:string;secondIcon?:string;secondAmount?:string};
const globalDefs:GlobalDef[]=[
 {id:'climb',title:'Grimpe toujours plus haut',icon:'ui-play',value:()=>SaveService.data.stats.levelsCompleted,thresholds:[10,20,30,50,75,100,150,200,300,500]},
 {id:'perfect',title:'Maître des étoiles',icon:'star-full',value:()=>Object.values(SaveService.data.progress).filter(p=>p.completed&&p.bestErrors===0).length,thresholds:[5,10,25,50,100,150,250]},
 {id:'claw',title:'Coup de griffe',icon:'ui-clock',value:()=>Object.entries(SaveService.data.progress).filter(([id,p])=>p.completed&&SaveService.data.journeyLevels[id]?.timed).length,thresholds:[1,3,5,10,20,30,50,75,100]},
 {id:'collection',title:'Collectionneur',icon:'hub-decorate',value:()=>SaveService.data.ownedCosmetics.length,thresholds:[3,5,10,15],collection:true},
];

export class MissionsScene extends Phaser.Scene {
 private tab:MissionTab='daily';
 constructor(){super('Missions');}
 init(data:{tab?:MissionTab}={}){this.tab=data.tab??'daily';}
 create(){
  this.cameras.main.setBackgroundColor(0xfff7ef);backButton(this,()=>this.scene.start('LevelSelect'));title(this,'Missions',90,58);label(this,540,150,'Relève des défis et fais grandir ta collection',26,'#78647d',18);
  const tabY=270,tabW=478,gap=24,startX=50;([{key:'daily' as const,name:'Missions du jour'},{key:'global' as const,name:'Missions globales'}]).forEach((t,i)=>{const active=this.tab===t.key,x=startX+tabW/2+i*(tabW+gap),c=this.add.container(x,tabY),skin=this.add.image(0,0,active?'button-primary':'button-secondary').setDisplaySize(tabW,112),txt=label(this,0,0,t.name,29,active?'#ffffff':C.ink,20);c.add([skin,txt]);if(!active)c.setAlpha(.88);press(this,c,tabW,112,()=>this.scene.restart({tab:t.key}));});if(this.tab==='daily')this.daily();else this.global();
 }
 private reward(x:number,y:number,reward:MissionReward){imageContain(this.add.image(x,y,reward.icon),46,46);if(reward.amount)label(this,x+38,y,reward.amount,22,C.ink,18).setOrigin(0,.5);if(reward.secondIcon&&reward.secondAmount){imageContain(this.add.image(x+90,y,reward.secondIcon),42,42);label(this,x+125,y,reward.secondAmount,21,C.ink,18).setOrigin(0,.5);}}
 private missionRow(y:number,icon:string,name:string,subtitle:string,current:number,target:number,reward:MissionReward,ready:boolean,claimed:boolean,onClaim?:()=>void){const card=panel(this,540,y,980,206);if(ready&&!claimed)card.setTint(0xfff1cf);imageContain(this.add.image(135,y,icon),84,84);label(this,220,y-45,name,28,C.ink,18).setOrigin(0,.5);label(this,220,y-4,subtitle,20,'#78647d',17).setOrigin(0,.5);if(ready||claimed)imageContain(this.add.image(700,y-43,'ui-check'),36,36).setAlpha(claimed?.68:1);const ratio=Phaser.Math.Clamp(current/target,0,1),barX=220,barY=y+54,barW=410,barH=36,barCenter=barX+barW/2;this.add.image(barCenter,barY,'button-disabled').setDisplaySize(barW,barH).setAlpha(.7);if(ratio>0){const fill=this.add.image(barX,barY,'button-primary').setOrigin(0,.5).setDisplaySize(barW,barH);fill.setCrop(0,0,fill.width*ratio,fill.height);}label(this,barCenter,barY,`${Math.min(current,target)} / ${target}`,19,ratio>.56?'#ffffff':C.ink,16);this.reward(785,y-12,reward);const action=this.add.container(850,y+55),completeState=claimed&&reward.icon==='ui-check',light=claimed||!ready,skin=this.add.image(0,0,ready&&!claimed?'button-primary':'button-disabled').setDisplaySize(230,66),txt=label(this,completeState?12:0,0,completeState?'Terminé':claimed?'Récupéré':ready?'Récupérer':'En cours',19,light?C.ink:'#ffffff',16);action.add(skin);if(completeState)action.add(imageContain(this.add.image(-72,0,'ui-check'),30,30));else if(ready&&!claimed)action.add(imageContain(this.add.image(-78,0,'ui-gift'),30,30));action.add(txt);if(ready&&!claimed&&onClaim)press(this,action,230,66,onClaim);}
 private daily(){const daily=SaveService.ensureDailyMissions();daily.missions.forEach((m,i)=>this.missionRow(530+i*260,m.family==='challenge'?'ui-clock':m.family==='mastery'?'star-full':'ui-play',m.title,m.subtitle,m.progress,m.target,{icon:'hub-diamond',amount:'1'},m.progress>=m.target,m.claimed,()=>{if(SaveService.claimDaily(m.id))this.scene.restart({tab:'daily'});}));}
 private global(){const maxCollection=cosmetics.length;globalDefs.forEach((def,i)=>{const value=def.value(),claimed=SaveService.data.missions.globalClaimed[def.id]??0,thresholds=def.collection?[...def.thresholds.filter(n=>n<maxCollection),maxCollection]:def.thresholds,next=thresholds.find(n=>n>claimed),y=500+i*260;if(!next){this.missionRow(y,def.icon,def.title,def.collection?'Collection complète':'Tous les paliers atteints',value,Math.max(1,thresholds.at(-1)??1),{icon:'ui-check',amount:''},true,true);return;}const milestoneIndex=thresholds.indexOf(next),diamonds=(milestoneIndex+1)%4===0?2:0,kibble=50+milestoneIndex*25,reward:MissionReward=diamonds?{icon:'hub-kibble',amount:String(kibble),secondIcon:'hub-diamond',secondAmount:String(diamonds)}:{icon:'hub-kibble',amount:String(kibble)};this.missionRow(y,def.icon,def.title,def.collection?`Découvre ${next} objets`:`Atteins le palier ${next}`,value,next,reward,value>=next,false,()=>{if(SaveService.claimGlobal(def.id,next,kibble,diamonds))this.scene.restart({tab:'global'});});});}
}
