import Phaser from 'phaser';
import { humanHint } from '../../core/humanSolver';
import { hintCost,MAX_HINTS_PER_ATTEMPT } from '../../core/economy';
import { isWon } from '../../core/validator';
import { AudioService } from '../../services/AudioService';
import { HapticsService } from '../../services/HapticsService';
import { SaveService } from '../../services/SaveService';
import { BoardView } from '../BoardView';
import { GameRegistry } from '../registry';
import { button,cozyBackground,fadeIn,imageContain,label,panel,sparkles } from '../ui';
import { C } from '../theme';

export class GameScene extends Phaser.Scene {
 private hints=0;private won=false;
 constructor(){super('Game');}
 create(){
  this.hints=0;this.won=false;this.registry.set('mapDragging',false);
  const level=GameRegistry.selected;if(!level||!SaveService.isUnlocked(level.id)){this.scene.start('LevelSelect');return;}
  fadeIn(this);cozyBackground(this);
  const artPanel=(x:number,y:number,w:number,h:number)=>this.add.image(x,y,'puzzle-panel').setDisplaySize(w,h);
  const artButton=(x:number,y:number,w:number,text:string,onClick:()=>void,primary=true)=>{const c=this.add.container(x,y),skin=this.add.image(0,0,primary?'button-primary':'button-secondary').setDisplaySize(w,112),txt=label(this,0,-2,text,32,primary?'#ffffff':C.ink);c.add([skin,txt]);c.setSize(w,120).setInteractive({useHandCursor:true});c.on('pointerdown',()=>{c.setScale(.965);c.setAlpha(.9);});c.on('pointerout',()=>{c.setScale(1);c.setAlpha(1);});c.on('pointerup',(p:Phaser.Input.Pointer)=>{c.setScale(1);c.setAlpha(1);if(p.getDistance()>32)return;AudioService.play('button');onClick();});return c;};
  const levelNumber=Number(level.id.split('-')[1]);artPanel(540,116,650,126);label(this,540,92,`${level.id.startsWith('bonus-')?'Défi bonus':'Niveau'} ${levelNumber}`,42);label(this,540,140,level.timed?'Coup de griffe · 5 min':'Puzzle des chats',24,'#775F68',24);
  const saved=SaveService.data.session;let remaining=saved?.id===level.id?saved.remaining??level.timeLimit??360:level.timeLimit??360;let started=saved?.id===level.id?!!saved.started:false;const markStarted=()=>{if(!started){started=true;SaveService.trackAttemptStart(level.id);}};const quit=()=>{SaveService.restartAttempt();this.scene.start('LevelSelect');};
  const confirmQuit=()=>{if(!started){quit();return;}const shade=this.add.rectangle(540,960,1080,1920,0x453c51,.72).setDepth(300).setInteractive();const card=panel(this,540,930,900,620).setDepth(301);const heading=label(this,540,730,'Quitter ce niveau ?',48).setDepth(302);const detail=label(this,540,900,'Ta progression sur cette tentative sera perdue :\ngrille, erreurs, chrono et indices.',32).setDepth(302);const stay=button(this,540,1080,690,'Continuer la partie',()=>{[shade,card,heading,detail,stay,leave].forEach(o=>o.destroy());},C.teal).setDepth(302);const leave=button(this,540,1240,690,'Quitter et recommencer plus tard',()=>{SaveService.trackAbandon(level.id);quit();},0xb398a5).setDepth(302);};
  artButton(95,116,145,'‹',confirmQuit,false);artButton(985,116,145,'?',()=>{this.scene.pause();this.scene.launch('Rules',{fromGame:true});},false);
  const clock=label(this,540,202,'',32);const onboarding=level.id.startsWith('trail-')?levelNumber:0;let ruleBottom=235;
  if(onboarding>=1&&onboarding<=5){const lines=['Autant de chats gris que de chats roux dans chaque ligne et chaque colonne.'];if(onboarding>=2)lines.push('♥  Le cœur relie deux chats identiques.');if(onboarding>=3)lines.push('Jamais trois chats identiques à la suite.');if(onboarding>=4)lines.push('Griffes : les deux chats sont différents.');const ruleH=onboarding>=4?270:onboarding>=3?220:onboarding>=2?180:145,ruleY=265+ruleH/2;ruleBottom=ruleY+ruleH/2+25;artPanel(540,ruleY,950,ruleH);imageContain(this.add.image(118,ruleY,'grey-cat'),62,62);imageContain(this.add.image(962,ruleY,'orange-cat'),62,62);const text=label(this,540,ruleY,lines.join('\n'),onboarding>=4?23:25);text.setLineSpacing(8).setWordWrapWidth(720,true);}
  const boardSize=onboarding?Math.min(840,1760-ruleBottom-430):900;const boardY=ruleBottom+boardSize/2+18;const board=new BoardView(this,540,boardY,level,boardSize);
  if(saved?.id===level.id&&saved.failed){this.scene.start('Lost',{reason:saved.remaining===0?'time':'errors'});return;}if(saved?.id===level.id){board.restore(saved.grid,saved.errors);this.hints=Math.max(0,saved.hints);}board.onAttempt=markStarted;board.onPlacement=(correct)=>SaveService.trackPlacement(level.id,correct);
  const lose=(reason:'errors'|'time')=>{board.locked=true;SaveService.data.failures[level.id]=(SaveService.data.failures[level.id]??0)+1;SaveService.trackFailure(level.id,reason);SaveService.remember(level.id,board.grid,board.errors,this.hints,remaining,started,true);this.scene.start('Lost',{reason});};
  if(level.timed){const clockText=()=>clock.setText(`◷ ${Math.floor(remaining/60)}:${String(Math.ceil(remaining%60)).padStart(2,'0')}${started?'':' · démarre au premier chat'}`);clockText();this.time.addEvent({delay:1000,loop:true,callback:()=>{if(!started||this.won||document.hidden)return;remaining=Math.max(0,remaining-1);clockText();SaveService.remember(level.id,board.grid,board.errors,this.hints,remaining,started);if(remaining===0){this.won=true;lose('time');}}});}
  const selectorY=boardY+boardSize/2+105;artPanel(540,selectorY,760,170);const selectorCards:Phaser.GameObjects.Container[]=[];const select=(value:1|2)=>{board.brush=value;selectorCards.forEach((c,i)=>{c.setScale(i+1===value?1.04:1);c.setAlpha(i+1===value?1:.76);const skin=c.list[0] as Phaser.GameObjects.Image;skin.setTexture(i+1===value?'cell-selected':'button-secondary');});};
  ([1,2] as const).forEach((value,i)=>{const c=this.add.container(350+i*380,selectorY),bg=this.add.image(0,0,'button-secondary').setDisplaySize(300,124),cat=imageContain(this.add.image(-68,0,value===1?'grey-cat':'orange-cat'),90,90),name=label(this,60,-16,value===1?'Nimbus':'Moka',30),kind=label(this,60,24,value===1?'Chat gris':'Chat roux',22,'#7A6470',22);c.add([bg,cat,name,kind]);c.setSize(310,130).setInteractive({useHandCursor:true}).on('pointerdown',()=>{if(!this.won)select(value);});selectorCards.push(c);});select(1);
  const usedHints=new Set<string>(saved?.id===level.id?saved.hintPositions:[]);const footerY=Math.min(1800,selectorY+190);const heart=this.add.image(850,116,'heart-full').setDisplaySize(108,108);const kibble=label(this,855,footerY,'',27);const status=label(this,540,footerY-105,'',26);const hintQuota=this.add.graphics();let previousErrors=board.errors;
  const setHeart=()=>{heart.setTexture(board.errors<=0?'heart-full':board.errors===1?'heart-crack-1':board.errors===2?'heart-crack-2':'heart-broken');};
  const drawHintQuota=()=>{hintQuota.clear();for(let i=0;i<MAX_HINTS_PER_ATTEMPT;i++){const used=i<SaveService.data.attemptPurchases;hintQuota.fillStyle(used?0xb8a8b4:0xffffff,used?.58:1).fillCircle(690+i*32,footerY+56,8);}};
  const hintLabel=()=>{const purchase=SaveService.data.attemptPurchases,cost=hintCost(purchase);return purchase>=MAX_HINTS_PER_ATTEMPT?'Indices épuisés':`Indice · ${cost} croquettes`;};
  const openHint=()=>{if(this.won||SaveService.data.attemptPurchases>=MAX_HINTS_PER_ATTEMPT)return;const found=humanHint(board.grid,level.constraints,1);this.scene.pause();this.scene.launch('Hint',{step:found,levelId:level.id,onPurchased:()=>{markStarted();SaveService.trackHint(level.id);SaveService.remember(level.id,board.grid,board.errors,this.hints,remaining,started,false,[...usedHints]);},onRead:()=>{const key=found?found.position.join(','):'';if(key&&!usedHints.has(key)){usedHints.add(key);this.hints++;SaveService.remember(level.id,board.grid,board.errors,this.hints,remaining,started,false,[...usedHints]);}},apply:()=>{if(this.won||!found)return;board.reveal(found.position,found.value);AudioService.play('hint');}});};
  const hint=artButton(390,footerY,520,hintLabel(),openHint,true);const hintText=hint.list.find(o=>o instanceof Phaser.GameObjects.Text) as Phaser.GameObjects.Text;const updateHintButton=()=>{const exhausted=SaveService.data.attemptPurchases>=MAX_HINTS_PER_ATTEMPT;hintText.setText(hintLabel());if(exhausted){hint.disableInteractive().setAlpha(.44);}else{hint.setInteractive({useHandCursor:true}).setAlpha(1);}};
  const changed=()=>{status.setText('');kibble.setText(`${SaveService.data.kibble} croquettes`);setHeart();drawHintQuota();updateHintButton();if(board.errors>previousErrors&&!SaveService.data.settings.reducedMotion){heart.setScale(1);this.tweens.add({targets:heart,scaleX:1.14,scaleY:1.14,duration:120,yoyo:true,ease:'Sine.Out'});}previousErrors=board.errors;if(!started&&board.grid.some((row,r)=>row.some((v,c)=>v!==level.initial[r]![c])))markStarted();SaveService.remember(level.id,board.grid,board.errors,this.hints,remaining,started);if(board.errors>=3&&!this.won){this.won=true;board.locked=true;this.time.delayedCall(SaveService.data.settings.reducedMotion?50:360,()=>{if(this.scene.isActive())lose('errors');});return;}if(isWon(board.grid,level.constraints)&&!this.won){this.won=true;board.locked=true;hint.disableInteractive();SaveService.trackWin(level.id);GameRegistry.result={level,errors:board.errors,hints:this.hints};AudioService.play('victory');void HapticsService.victory();sparkles(this,540,boardY,24);status.setText('Tout le monde a trouvé sa place !');void SaveService.complete(level.id,board.errors,this.hints).then(()=>{if(this.scene.isActive())this.time.delayedCall(SaveService.data.settings.reducedMotion?100:650,()=>this.scene.start('Victory'));});}};
  if(level.timed&&!started){board.locked=true;const cover=this.add.rectangle(540,960,1080,1920,0x453c51,.7).setDepth(200).setInteractive();const card=panel(this,540,930,920,690).setDepth(201);const heading=label(this,540,710,'Défi coup de griffe',52).setDepth(202);const detail=label(this,540,940,`${Math.round(remaining/60)} minutes · 3 erreurs maximum\n\nLe chrono démarre au premier placement.\nTu peux recommencer gratuitement.`,34).setDepth(202);const go=button(this,540,1160,660,'Je suis prêt',()=>{[cover,card,heading,detail,go].forEach(o=>o.destroy());board.locked=false;}).setDepth(202);}
  board.onChanged=changed;this.events.on('resume',changed);this.events.once('shutdown',()=>this.events.off('resume',changed));changed();
 }
}
