import Phaser from 'phaser';
import { preloadMotion,registerMotion } from '../motion';
import { C,FONT } from '../theme';

export class PreloadScene extends Phaser.Scene{
 constructor(){super('Preload');}
 preload(){
  window.dispatchEvent(new Event('meowza-ready'));
  this.cameras.main.setBackgroundColor(C.cream);
  const logo=this.add.image(540,790,'meowza-logo');
  const logoScale=Math.min(620/logo.width,350/logo.height);logo.setScale(logoScale);
  const track=this.add.graphics().fillStyle(0xe4ddd7,1).fillRoundedRect(220,970,640,24,12);
  const bar=this.add.graphics();
  this.add.text(540,1060,'Les chats préparent leur arbre…',{fontFamily:FONT,fontSize:'30px',fontStyle:'bold',color:C.ink}).setOrigin(.5);
  this.load.on('progress',(v:number)=>bar.clear().fillStyle(C.teal).fillRoundedRect(220,970,640*v,24,12));
  this.load.once('complete',()=>{track.clear().fillStyle(0xe4ddd7,1).fillRoundedRect(220,970,640,24,12);bar.clear().fillStyle(C.teal).fillRoundedRect(220,970,640,24,12);});
  const img=(key:string,path:string)=>this.load.image(key,`assets/${path}`);
  img('home-background','backgrounds/home/home_background.png');img('room-background','backgrounds/home/room_background.png');img('background-salon','backgrounds/home/home_background.png');img('background-serre','backgrounds/home/background_serre.png');img('background-night','backgrounds/home/background_nuit.png');img('background-forest','backgrounds/custom/forest.svg');img('background-blossom','backgrounds/custom/blossom.svg');img('background-autumn','backgrounds/custom/autumn.svg');
  img('duo-home','characters/illustrations/duo_home.png');img('duo-retry','characters/illustrations/duo_retry.png');img('duo-victory','characters/illustrations/duo_victory.png');img('nimbus-reading','characters/illustrations/nimbus_reading.png');img('nimbus-sleeping','characters/illustrations/nimbus_sleeping.png');img('moka-playing','characters/illustrations/moka_playing.png');img('grey-cat','characters/nimbus/static/nimbus_token.png');img('orange-cat','characters/moka/static/moka_token.png');
  const ui:Record<string,string>={'button-primary':'ui/button_primary.png','button-secondary':'ui/button_secondary.png','button-disabled':'ui/button_disabled.png','puzzle-panel':'ui/panel.png','button-square':'ui/tile_ivory.png','tile-peach':'ui/tile_peach.png','tile-lilac':'ui/tile_lilac.png','ui-circle':'ui/circle.png','cell-empty':'puzzle/cell_outline_peach.png','cell-selected':'puzzle/cell_outline_teal.png','cell-hint':'ui/tile_peach.png','cell-error':'ui/tile_peach.png','heart-full':'ui/icons/heart.png','heart-crack-1':'ui/icons/heart_cracked.png','heart-crack-2':'ui/icons/heart_damaged.png','heart-broken':'ui/icons/heart_broken.png','hub-diamond':'ui/diamond.png','hub-kibble':'ui/kibble.png','hub-settings':'ui/gear.png','hub-missions':'ui/missions.png','hub-shop':'ui/shop.png','hub-decorate':'ui/decorate.png','hub-daily':'ui/daily.png','hub-locate':'ui/icons/play.png','ui-back':'ui/back.png','ui-close':'ui/close.png','ui-check':'ui/check.png','ui-lock':'ui/icons/lock.png','ui-play':'ui/icons/play.png','ui-pause':'ui/pause.png','ui-clock':'ui/icons/clock.png','ui-relation-heart':'ui/same.png','ui-relation-claws':'ui/different.png','ui-hint':'ui/hint.png','ui-calendar':'ui/calendar.png','ui-medal':'ui/medal.png','ui-gift':'ui/gift.png','ui-gift-open':'ui/gift_open.png','ui-confetti':'ui/confetti.png','diamond-pile':'ui/diamonds_pile.png','diamond-pouch':'ui/diamonds_pouch.png','diamond-chest':'ui/diamonds_chest.png'};Object.entries(ui).forEach(([key,path])=>img(key,path));
  img('puzzle-board-frame','puzzle/board_frame_cream.png');img('puzzle-board-frame-wood','puzzle/board_frame_wood.png');img('cell-outline-peach','puzzle/cell_outline_peach.png');img('cell-outline-teal','puzzle/cell_outline_teal.png');img('tutorial-arrow','puzzle/tutorial_arrow.png');
  const plaques:Record<string,string>={'badge-easy':'progression/plaques/vert.png','badge-medium':'progression/plaques/bleu.png','badge-hard':'progression/plaques/orange.png','badge-extreme':'progression/plaques/rouge.png','badge-timed':'progression/plaques/violet.png','badge-current':'progression/plaques/selection.png','stars-1':'progression/stars/stars_1.png','stars-2':'progression/stars/stars_2.png','stars-3':'progression/stars/stars_3.png','star-empty':'progression/stars/star_empty.png','star-full':'progression/stars/star_full.png'};Object.entries(plaques).forEach(([key,path])=>img(key,path));
  const tree:Record<string,string>={'tree-base':'tree/base.png','tree-cloud':'tree/cloud.png','tree-post':'tree/post_repeat.png','tree-post-long':'tree/connectors/post_long.png','tree-post-short':'tree/connectors/post_short.png','tree-junction-t':'tree/connectors/post_connector_t.png','tree-junction-round':'tree/connectors/post_connector_round.png','tree-support-cream':'tree/support_fin_ivoire.png','tree-support-peach':'tree/support_fin_peche.png','tree-hammock-bar':'tree/traverse_hamac.png','tree-hammock':'tree/hammock.png','tree-cubby':'tree/niche_collection.png','tree-hammock-lilac':'tree/decor/hamac_lilas.png','tree-hammock-peach':'tree/decor/hamac_peche.png','tree-cubby-cream':'tree/decor/niche_creme.png','tree-cubby-wood':'tree/decor/niche_bois.png','tree-plant':'tree/decor/potted_plant.png','tree-hanging-plant':'tree/decor/hanging_plant.png','tree-yarn':'tree/decor/yarn_peach.png','tree-flower-cushion':'tree/flower_cushion.png','tree-moon-cushion':'tree/moon_cushion.png','tree-flower-cubby':'tree/flower_cubby.png','tree-moon-cubby':'tree/moon_cubby.png','tree-flower-hammock':'tree/flower_hammock.png','tree-moon-hammock':'tree/moon_hammock.png'};Object.entries(tree).forEach(([key,path])=>img(key,path));
  for(const cat of ['noisette','domino','astre','opale','orion','perle'])img(`collection-${cat}`,`collection/cats/cat_${cat}.png`);
  preloadMotion(this);
 }
 create(){registerMotion(this);this.scene.start('Home');}
}
