import test from 'node:test';
import assert from 'node:assert/strict';
import { SaveServiceImpl } from '../services/SaveService';
import { hintCost } from './economy';
import { generateJourneyLevel } from './journey';
import { humanSolve } from './humanSolver';
const memory=()=>new SaveServiceImpl({get:async()=>({value:null}),set:async()=>{}});
test('every distinct level earns kibble once, replay does not',async()=>{const s=memory();await s.complete('easy-01',3,0,0);assert.equal(s.data.kibble,65);await s.complete('easy-02',3,0,0);assert.equal(s.data.kibble,70);await s.complete('easy-01',3,0,0);assert.equal(s.data.kibble,70);assert.equal(s.data.lastReward,0);});
test('hints escalate, remain owned after restart, cannot overspend',()=>{const s=memory();const h={position:[0,0] as const,value:1 as const,rule:'balance' as const,sources:[],explanation:'Balance'};assert.equal(s.buyHint('trail-1',h),true);assert.equal(s.data.kibble,40);assert.equal(hintCost(s.data.attemptPurchases),35);assert.equal(s.buyHint('trail-1',h),true);assert.equal(s.data.kibble,40);s.restartAttempt();assert.equal(s.buyHint('trail-1',h),true);assert.equal(s.data.kibble,40);s.data.kibble=0;assert.equal(s.buyHint('trail-2',h),false);});
test('extreme proofs are short, single-depth, limited and genuinely needed',()=>{for(let n=1;n<=12;n++){const l=generateJourneyLevel(n,true),r=humanSolve(l.initial,l.constraints,1);assert.equal(r.status,'solved',String(n));assert.equal(humanSolve(l.initial,l.constraints,0).status,'stuck');const hypotheses=r.steps.filter(s=>s.rule==='contradiction');assert.ok(hypotheses.length<=3);for(const h of hypotheses){assert.ok(h.consequences!.length<=5);assert.ok(h.consequences!.every(s=>s.rule!=='contradiction'));}}});
